#pragma once
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_event.h"
#include "esp_log.h"
//#include "esp_http_server.h"
#include "esp_netif.h"
#include "driver/i2s_std.h"
#include "esp32_s3_szp.h"
#include "sdkconfig.h"
#include "esp_check.h"
//#include "esp_vfs_fat.h"
#include "sdmmc_cmd.h"
#include "driver/sdmmc_host.h"
#include "freertos/event_groups.h"
#include "lwip/sockets.h"
#include <stdlib.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include "driver/i2s_common.h"
#include <arpa/inet.h>
void app_audio(void);